image: node:18.19.0-alpine

stages:
- build
- test
- deploy

cache:
  paths:
  - node_modules
  - build

build-job:
  stage: build
  script:
  - npm install
  - npm run build
  # 制品目录
  artifacts:
    paths:
    - /docs/.vuepress/dist

test-job:
  stage: test
  script:
  - git --version
  - node -v
  - npm -v

deploy-job-dev:
  stage: deploy
  script:
  - sshpass -p $PWD ssh root@$DYIP "pwd;cd /opt/vuepress;git pull;npm install;npm run build"
  artifacts:
    paths:
    - ./docs/.vuepress/dist

deploy-job-prod:
  stage: deploy
  script:
  - npm install
  - npm run build
  when: manual
