image: node:18.19.0

stages:
- build
- deploy

cache:
  paths:
  - node_modules

build-job:
  stage: build
  script:
  - npm install
  - npm run build
  artifacts:
    paths:
    - /docs/.vuepress/dist


deploy-job-dev:
  stage: deploy
  image: ringcentral/sshpass:latest
  script:
  - ls
  - pwd
  - sshpass -p $PWD ssh -o StrictHostKeyChecking=no root@$DYIP "pwd;ls;"
  - sshpass -p $PWD ssh root@$SERVER_IP
  - sshpass -p $PWD scp -r ./* root@$SERVER_IP:/opt/temp
  only:
  - main

deploy-job-prod:
  stage: deploy
  script:
  - npm install
  - npm run build
  when: manual
